version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///./makesalot.db
      - SECRET_KEY=${SECRET_KEY}
      - CHROME_EXTENSION_URL=${CHROME_EXTENSION_URL}
      - SENTRY_DSN=${SENTRY_DSN}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
