services:
  - type: web
    name: makesalot-api
    env: python
    plan: free
    buildCommand: "python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHONUNBUFFERED
        value: "1"