services:
  - type: web
    name: makesalot-api
    env: python
    plan: free
    pythonVersion: "3.11"  # Changed from 3.13 to 3.11 for better compatibility
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false