services:
  - type: web
    name: makesalot-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0